# Generated by Django 4.1.6 on 2023-05-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctholders', '0006_alter_acctholders_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=55)),
                ('trans_typ', models.CharField(max_length=55)),
                ('amount', models.CharField(max_length=55)),
                ('date', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
