# Generated by Django 4.2 on 2023-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acctholders', '0005_acctholders_acc_typ_acctholders_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acctholders',
            name='balance',
            field=models.IntegerField(null='True'),
        ),
    ]
